sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t 1919sai/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true 1919sai/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'docker'
  env: 'docker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-279573027662'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACESS_KEY
  secret_access_key: $AWS_SECRET_KEY
